DROP TABLE IF EXISTS `artists`;
CREATE TABLE `artists` (
  `id` INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS `works`;
CREATE TABLE `works` (
  `id` INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS `locations`;
CREATE TABLE `locations` (
  `id` INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL
);